#!/usr/bin/python3

'''
    Author        : Paul Onions
    Creation date : 30 June 2016

    COMMERCIAL IN CONFIDENCE
    (C) 2016 Silicon Infusion Limited

    Silicon Infusion Limited                 
    CP House
    Otterspool Way
    Watford WD25 8HP
    Hertfordshire, UK
    Tel: +44 (0)1923 650404
    Fax: +44 (0)1923 650374
    Web: www.siliconinfusion.com

    This is an unpublished work the copyright of which vests in Silicon Infusion
    Limited. All rights reserved. The information contained herein is the
    property of Silicon Infusion Limited and is supplied without liability for
    errors or omissions. No part may be reproduced or used except as authorised
    by contract or other written permission. The copyright and the foregoing
    restriction on reproduction and use extend to all media in which the
    information may be embodied.

    Read a register over the Zwire SPI interface.
'''

import os
import sys

import zwire

if len(sys.argv) != 3:
    print '''usage: zwspiread <dspi_number> <address>'''
    exit(1)

dspi    = int(sys.argv[1],0)
address = int(sys.argv[2],0)

zwire = zwire.ZwireSPI(dspi)

zwire.open()

rddat = zwire.read(address)
print 'READ : 0x{0:08x} : '.format(address), '0x{0:08x}'.format(rddat)

zwire.close()
