#!/usr/bin/python3

##
##  Author        : Paul Onions
##  Creation date : 30 June 2016
##
##  COMMERCIAL IN CONFIDENCE
##  (C) 2016 Silicon Infusion Limited
##
##  Silicon Infusion Limited                 
##  CP House
##  Otterspool Way
##  Watford WD25 8HP
##  Hertfordshire, UK
##  Tel: +44 (0)1923 650404
##  Fax: +44 (0)1923 650374
##  Web: www.siliconinfusion.com
##
##  Licence: MIT, see LICENCE file for details.
##

##
##  Write to a register over the Zwire SPI interface.
##

import os
import sys

import zaltys_zwire

if len(sys.argv) != 4:
    print('usage: zspiwrite <dspi_number> <address> <data>')
    exit(1)

dspi    = int(sys.argv[1],0)
address = int(sys.argv[2],0)
wrdat   = int(sys.argv[3],0)

zwire = zaltys_zwire.ZwireSPI(dspi)

zwire.open()

zwire.write(address, wrdat)
print('WRITE: 0x{0:01x}'.format(dspi), '0x{0:08x}'.format(address), '0x{0:08x}'.format(wrdat))

zwire.close()
